- .github/workflows/ios.yml
- Source/AdmiralSwiftUI/Classes/Components/Views/Chat/UploadFIleView/Document/Group/UploadDocumentGrid.swift
- fastlane/Fastfile
- fastlane/build_info.rb
- fastlane/go_scripts/buildInfo.go
- fastlane/go_scripts/issues/createIssueComment.go
- fastlane/go_scripts/main.go
- Добавить добавлений комментарий о сборке к Pull Request
- Изменены скрипты 
-
-
**Иван Алмазов
**Кирилл Борисов
**Андрей Дятков
**Лара Маркова
> [68] - Added Comments to Pull Request

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
Add export for build scripts
---
**Иван Алмазов
**Кирилл Борисов
**Андрей Дятков
**Лара Маркова
> [65] - Add export for build scripts

- README.md
**Иван Алмазов
**Кирилл Борисов
**Андрей Дятков
**Лара Маркова
> [TECH] - Update README.md

- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/PageControls/LinerPageControl/LinerPageControl.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/PageControls/PageControlsViewController.swift
Добавил page control Liner экран UIKit
Посмотреть в демо PageControl->Liner 
> [57] - Add page control screen

- .github/CODEOWNERS
Добавлены code owners чтобы они добавлялись в reviewers 
-
-
> [Tech] - Add code owners

- AdmiralSwiftUI.podspec
- AdmiralTheme.podspec
- AdmiralUIKit.podspec
- AdmiralUIResources.podspec
- ExampleiOS/Source/Supporting Files/Info.plist
- Source/AdmiralSwiftUI/Supporting Files/Info.plist
- Source/AdmiralTheme/Supporting Files/Info.plist
- Source/AdmiralUIKit/Supporting Files/Info.plist
- Source/AdmiralUIResources/Supporting Files/Info.plist
- Tests/AdmiralSwiftUITests/Supporting Files/Info.plist
- Tests/AdmiralUIKitTests/Supporting Files/Info.plist
- fastlane/README.md
- version.json
> [BUMP] - 6

- AdmiralSwiftUI.podspec
- AdmiralTheme.podspec
- AdmiralUIKit.podspec
- AdmiralUIResources.podspec
- ExampleiOS/Source/Supporting Files/Info.plist
- Source/AdmiralSwiftUI/Supporting Files/Info.plist
- Source/AdmiralTheme/Supporting Files/Info.plist
- Source/AdmiralUIKit/Supporting Files/Info.plist
- Source/AdmiralUIResources/Supporting Files/Info.plist
- Tests/AdmiralSwiftUITests/Supporting Files/Info.plist
- Tests/AdmiralUIKitTests/Supporting Files/Info.plist
- version.json
> [BUMP] - 7

- AdmiralSwiftUI.podspec
- AdmiralTheme.podspec
- AdmiralUIKit.podspec
- AdmiralUIResources.podspec
- README.md
Добавлена спецификация 
Добавлена спецификация 
-
> [158] - Added pod spec source

- Source/AdmiralUIKit/Classes/Components/Controls/Slider/DoubleSilder/DoubleSlider.swift
- Source/AdmiralUIKit/Classes/Components/Views/TextFields/DoubleInputRangeTextField/DoubleInputRangeTextField.swift
- Пофиксить баг с двойным слайдером в UIKit(При достижение минимального или максимального значения в двойном слайдере перестает работа ползунок)
- Пофиксить баг с полем Optional Label и Additional Text
- Исправлены Баги
- UIKit -> TextFields -> Slider
> [142] - Fixed Bug with DoubleSlider in UIKit

- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/UnderlineSliderTabs/UnderlineSliderTabs.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Tab/SlideTab/UnderlineSliderTab/BaseUnderlineSegmentedControl.swift
Дать возможность выбирать элементы в UnderlineTabs при выключенном скроллинге
Убрана строчка guard is  guard isScrollEnabled else { return }
UIKit -> Tabs -> UnderlineSliderTabs
> [175] - Segment control UIKit

- Source/AdmiralSwiftUI/Classes/Components/Views/TextFields/Sliders/DoubleInputRangeTextField/DoubleInputRangeTextField.swift
Убрать прыжки правого текстфилда в DoubleInputRangeTextField SwiftUI
Исправлен баг
SwiftUI -> Slider -> Double
> [34] - Fixed layout of right textfield in SwiftUI DoubleInputRangeTextField

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/ItemSwiftUIRow/SwiftUIItem.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/MainViewController.swift
Поправить ошибки в словах на главной странице 
Исправлены ошибки 
Главная -> проверить правильность написания слов 
Было:
Стало:
> [27] - Fixed grammatical error in Main Page

- Source/AdmiralUIKit/Classes/Components/Views/TextFields/TextView/TextView.swift
Trailing View in Textiew
Исправлено условие появления placeholder в Textiew
Проверить текстфилды на корректную работу UIKit
> [185] - Fix TextView

- ExampleiOS/Source/Classes/UserStrories/Common/View/Cells/MenuListCell.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Common/Cells/MainTitleTableViewCell.swift
Исправлено: Некорректное отображение наименование темы когда много символов
Исправлено: Некорректное отображение строки наименования названия темы
> [196,197] - Themes constraints

- Scripts/build_git_packages.command
Добавить скрипт для ручной сборки XCFrameWorks
Добавлен скрипт
-
> [202] - Added command script to build git_packages

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Informers/SmallInformers/SmallInformersSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/InformersAndToasts/Informers/SmallInformers/SmallInformersViewController.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Informers/SmallInformer/SmallInformer.swift
- Source/AdmiralUIKit/Classes/Components/Views/Informers/SmallInformer/SmallInformer.swift
Добавлена возможность выставить стрелку у SmallInformer в верхний правый и нижний левый угол. 
Добавлены 
- topRight - The arrow is at the top right
- bottomRight - The arrow is at the bottom right
Изменения коснулись SwiftUI/UIKit
Проверить SmallInformer SwiftUI/UIKit с фигмой
> [165] - Fix SmallInformer arrow image

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/ItemSwiftUIRow/SwiftUIItem.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/BottomSheet/BottomSheetViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/MainViewController.swift
Исправлены наименования разделов TextFields, RadioButton, Bottom Sheets 
Главный экран UIKit/SwiftUI
> [113] - Fix naming in main demo

- version.json
> [BUMP] - 7.0.0

- fastlane/Fastfile
- fastlane/go_scripts/main.go
- fastlane/go_scripts/pullRequests/linkPullRequest.go
Создать скрипт для автоматического закрытия Issue после вливания пулу реквеста
Добавлен скрипт
> [137] - Added Script to Link Pull Request

- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Toolbar/ToolbarViewController.swift
UIKit исправлен текст в тулбаре в демо "Количество пунктов меню" 
> [222] - Fix text toolbar

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/Logo/LogoTabSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/Standard/StandardTabSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/TabsSwiftUIView.swift
Убраны скролл бары в лого таб и стандарт таб
> [220] - Desable scroll bar

- Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/LogoTab/LogoTab.swift
Исправлен баг с анимацией для логотабс SwiftUI
Uploading Запись экрана 2022-05-24 в 11.08.15.mov…
> [224] - Fix animation duration

- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Calendar/Horizontal/HorizontalViewController.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/HorizontalCalendar/CalendarHorizontalView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/HorizontalCalendar/Cell/CalendarHorizontalViewCell.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/VerticalCalendar/CalendarVerticalView.swift
При первом нажатии на дату в календаре возвращается пустая дата.
Исправлены методы делегата
UIKit -> Calendar
> [241] - Fixed delegate methods of Set Dates

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/TabsSwiftUIItem.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/UnderlineSliderTab/UnderlineCenterTabsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/UnderlineSliderTab/UnderlineSliderTabSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/UnderlineSliderTab/UnderlineTabsSwiftUIItem.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/UnderlineSliderTab/UnderlineTabsUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/TabsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/UnderlineTabs/UnderlineCenterTabs/UnderlineCenterTabs.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/UnderlineTabs/UnderlineSliderTabs/UnderlineSliderTabs.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/UnderlineTabs/UnderlineTabsViewController.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/UnderlineSliderTab/UnderlineTab.swift
- Source/AdmiralSwiftUI/Classes/CoreFoundation/Rect/RectAwareViewModifier.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Tab/SlideTab/UnderlineSliderTab/BaseUnderlineSegmentedControl.swift
Реализованы задачи 
https://github.com/admiral-team/admiralui-ios/issues/225
https://github.com/admiral-team/admiralui-ios/issues/104
Баг с пересчетом фрейма на SwiftUI был найден в модификаторе preference для IOS 15
Добавлена навигация для Underline Tabs
Протестировать Underline Tabs в рамках вышеуказанных задач
> [225] - Underline tabs bugs & navigations

- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/InformersAndToasts/Informers/BigInformers/BigInformersController.swift
Удалена лишняя вью из демо
Проверить BigInformer in demo
> [229] - Remove view from BigInformer in demo

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/DropDown/DropDownSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/Link/LinkSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/Paragraph/ParagraphSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/Separator/SeparatorSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/TextBlocks/DropDown/DropDownViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/TextBlocks/Links/LinksHeaderViewController.swift
- Source/AdmiralUIKit/Classes/Components/Views/TextBlock/Headers/DropDown/ButtonDropDown/ButtonDropDown.swift
- Source/AdmiralUIKit/Classes/Components/Views/TextBlock/Headers/DropDown/TitleButtonDropDown/TitleButtonDropDown.swift
- Source/AdmiralUIKit/Classes/Components/Views/TextBlock/Headers/Link/LinkViewHeader.swift
https://github.com/admiral-team/admiralui-ios/issues/102
Headers с Настей решили оставить как есть в приложении, остальное добавил.
На недостающие элементы нужно завести задачи.
Протестировать Text Blocks
> [102] - Fix text blocks

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/SwiftUIController.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Toast/ToastPresenter.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Toast/ZToastNotificationsView.swift
SwiftUI
https://github.com/admiral-team/admiralui-ios/issues/223
https://github.com/admiral-team/admiralui-ios/issues/221
Добавлен интерфейс (замыкание), которое вызывается когда показались все тосты.
В результате есть возможность удалить данные из модели.
Протестировать в notifications SwiftUI
> [221] - Fix Notification

- Source/AdmiralUIKit/Classes/Components/Views/Cell/ActionBarCell/ActionCellView.swift
https://github.com/admiral-team/admiralui-ios/issues/101
Протестировать свайп
> [101] - Fix action bar cell

- fastlane/README.md
- version.json
> [BUMP] - 9.0.0

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/UnderlineSliderTab/UnderlineSliderTabSwiftUIView.swift
https://github.com/admiral-team/admiralui-ios/issues/275
> [275] - Fix name Slider controls

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/ActionBar/ActionBarSwiftUIView.swift
https://github.com/admiral-team/admiralui-ios/issues/255
Проверить  action bar
> [255] - Fix action bar icons

- .github/workflows/ios.yml
- fastlane/Fastfile
- fastlane/go_scripts/buildInfo.go
- fastlane/go_scripts/main.go
- fastlane/go_scripts/telegram/sendMessage.go
- Поправить скрипт добавления релиза
> [282] - Release script fix

- version.json
> [BUMP] - 9.1.0

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Notifications /ToastNotifications/ToastNotificationsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Themes/ThemeViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Themes/ThemesViewController.swift
Убрать возможность добавления пустой темы
Убрана возможность добавления пустой темы
Main -> Themes
> [274] - Remove adding empty theme title

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Alert&Onboarding/Alert/AlertSwiftUIView.swift
https://github.com/admiral-team/admiralui-ios/issues/276
> [276] - Fix animation Alert SwiftUI

- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/UnderlineTabs/UnderlineTabsViewController.swift
https://github.com/admiral-team/admiralui-ios/issues/292
> [292] - Fix slider UIKit

- version.json
> [BUMP] - 10.0.0

- ExampleiOS/Source/Classes/UserStrories/Chat/SwiftUI/UploadingPhoto/SwiftUIUploadingPhotoViewModel.swift
- ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/UploadingImage/UploadingImageViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/IconTabs/IconTabs.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/InformerTabs/InformerTabSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/Logo/LogoTabSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/OutlineSliderTab/OutlineSliderTabSwiftUITab.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/Standard/StandardTabSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/UnderlineSliderTab/UnderlineSliderTabSwiftUIView.swift
Реализовать следующие задачи:
#306 
#307 
#309
- Поправлены нэйминги
- Добавлены экшены к нажатию на UplodingImage
SwiftUI/UIKit -> Chat -> Uploading Photo
Tabs -> Naming
> [306] - Added actions for Uploading Photos & Fixes naming

- version.json
> [BUMP] - 10.1.0

- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIIconsTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitButtonsTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitTests.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitTestsLaunchTests.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUITextBlocksTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIThemesTest.swift
Добавить автотесты для Themes, Icons
Добавил автотесты UI для экранов Themes, Icons, Buttons
> [331] - Add Themes, Icons, Buttons UI Tests

- ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/Input/Cell/ChatMessageCell.swift
- ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/Input/InputChatViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/TextOperation/Cell/TextOperationCell.swift
- ExampleiOS/Source/Classes/UserStrories/Chat/UIKIt/UploadingFile/Cell/UploadingFileCell.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/MapButtons/List/Cell/MapButtonCellView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/TextBlocks/Paragraph/Views/ParagraphCellView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Cell/TableViewCell/TableListCell.swift
- Source/AdmiralUIKit/Classes/Components/Views/Cell/View/Traling/CheckBoxListView/CheckBoxListView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/ChatBubbleStatusView/ChatBubbleStatusView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/ChatBubbleView/ChatBubbleView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/ChatInput/ChatInputView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/ProgressView/ProgressView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/TextOperation/TextOperationView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/UploadFileView/Document/UploadDocumentView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/UploadImageView/Grid/UploadImageGrid.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/UploadImageView/UploadImageView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Toast/ToastView/ToastView.swift
https://github.com/admiral-team/admiralui-ios/issues/347
> [347] - Remove automanage from elements

- .github/workflows/ios.yml
- Source/AdmiralSwiftUI/Classes/Components/Controls/Map/MapButtonScheme.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/Map/MapButtonStyle.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/PageControl/CirclePageControl/CirclePageControl.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/PageControl/CirclePageControl/CirclePageControlScheme.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/PageControl/LinerPageControl/LinePageControllScheme.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/PageControl/LinerPageControl/LinerPageControll.swift
- fastlane/Fastfile
- Добавить документацию
- Расширить схемы
- Убрать view из схем
SwiftUI:
- CirclePageControl
- LinearPageControl
- MapButtonStyle
> [429] - SwiftUI Controls Refactoring

- Source/AdmiralSwiftUI/Classes/Components/Views/Toast/ToastPresenter.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Toast/ZToastNotificationsView.swift
SwiftUI ToastView 
SwiftUI ToastView 
SwiftUI ToastView 
> [392] - SwiftUI ToastView Refactoring 

- Source/AdmiralSwiftUI/Classes/Components/Views/Chat/UploadFIleView/Image/Group/UploadingImageGrid.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Chat/UploadFIleView/Image/UploadImageView.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Chat/UploadFIleView/Image/UploadImageViewScheme.swift
swiftUI -> UploadImageView
swiftUI -> UploadImageView
swiftUI -> Chat -> Image
> [392] - SwiftUI Refactoring Views UploadImageView

- Source/AdmiralUIKit/Classes/Components/Controls/CheckControl/CheckBox/CheckBox.swift
- Source/AdmiralUIKit/Classes/Components/Controls/CheckControl/CheckControl.swift
- Source/AdmiralUIKit/Classes/Components/Controls/CheckControl/CheckTextControl/CheckTextControl.swift
- Source/AdmiralUIKit/Classes/Components/Controls/CheckControl/RadioControl/RadioControl.swift
https://github.com/admiral-team/admiralui-ios/issues/360
https://github.com/admiral-team/admiralui-ios/issues/361
https://github.com/admiral-team/admiralui-ios/issues/373
> [360] - Add check Control documentation

- version.json
> [BUMP] - 11.0.0

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Shimmers/ShimmersSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Shimmers/ShimmerCellView.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Cell/ListCell/ListCell.swift
https://github.com/admiral-team/admiralui-ios/issues/470
Исправлены отступы UIKit SwiftUI
UIKit - edgeInsets у ListCell в соответствии с фигмой
> [470] - Fix shimmers UIKit, SwiftUI

- Source/AdmiralUIKit/Classes/Components/Views/Chat/ChatBubbleStatusView/ChatBubbleStatusViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/ChatBubbleView/ChatBubbleView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/ChatBubbleView/ChatBubbleViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/ChatInput/ChatInputTextFieldScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/ChatInput/ChatInputView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/ProgressView/Loading/CircularTrackView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/ProgressView/Loading/CircularTrackViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/ProgressView/ProgressViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/TextOperation/TextOperationView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/TextOperation/TextOperationViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/UploadFileView/Document/UploadDocumentView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/UploadFileView/Document/UploadDocumentViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/UploadImageView/Grid/UploadImageGrid.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/UploadImageView/Grid/UploadImageGridScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/UploadImageView/UploadImageView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Chat/UploadImageView/UploadImageViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/ErrorView/ErrorView.swift
- Source/AdmiralUIKit/Classes/Components/Views/ErrorView/ErrorViewScheme.swift
Чат color scheme публичными
Чат UIKit
> [606] - Chat color schemes

- Source/AdmiralUIKit/Classes/Components/Controls/Map/MapButton.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Map/MapButtonScheme.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Pin/PinButton.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Pin/PinButtonScheme.swift
- Source/AdmiralUIKit/Classes/Components/Controls/SeveralPin/SeveralPinButton.swift
- Source/AdmiralUIKit/Classes/Components/Controls/SeveralPin/SeveralPinButtonScheme.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Slider/DoubleSilder/DoubleSlider.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Slider/Slider/Slider.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Slider/SliderScheme.swift
Maps controls schemes
Map элементы
> [606] - Maps controls schemes

- Source/AdmiralUIKit/Classes/Components/Views/Informers/BigInformer/BigInformer.swift
Изменил метод в интерфейсе BigInformerDelegate, добавил параметр bigInformer. 
BigInformer UIKit
> [548] - Change interface for big informer

- Source/AdmiralUIKit/Classes/Components/Views/Calendar/CalendarView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/CalendarViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/Common/Cells/CalendarViewCell.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/Common/Cells/CalendarViewCellColorScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/Common/Views/CalendarHorizontalHeaderView/ButtonWithArrowScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/Common/Views/CalendarHorizontalHeaderView/CalendarHorizontalHeaderViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/Common/Views/FooterView/CalendarFooterViewColorScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/Common/Views/HeaderView/CalendarHeaderViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/Common/Views/MonthYearPickerView/MonthYearPickerViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/HorizontalCalendar/CalendarHorizontalViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/HorizontalCalendar/Cell/CalendarHorizontalViewCellScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/VerticalCalendar/CalendarVerticalViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/Card/CardView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Card/CardViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/SearchBar/SearchBar.swift
- Source/AdmiralUIKit/Classes/Components/Views/SearchBar/SearchBarColorScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/StatusHistory/StatusHistoryDateView/StatusHistoryDateViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/StatusHistory/StatusHistoryImagesView/StatusHistoryBaseImagesViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/StatusHistory/StatusHistoryStatusView/StatusHistoryStatusViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/StatusHistory/StatusHistorySummaView/StatusHistorySumViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/StatusHistory/StatusHistoryTitleView/StatusHistoryTitleViewScheme.swift
- Source/AdmiralUIKit/Classes/Components/Views/StatusHistory/StatusHistoryView.swift
- Source/AdmiralUIKit/Classes/Components/Views/StatusHistory/StatusHistoryViewScheme.swift
Calendar schemes UIKIt
Calendar UIKIt
> [606] - Calendar schemes

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/GhostButton/GhostButtonSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/Otherbuttons/OtherButtonsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/PrimaryButtons/PrimaryButtonsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/Rules/RulesSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/SecondaryButtons/SecondaryButtonsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/Representable/ThemeSwitchView/ThemeSwitchSwiftUIView.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/StandardTab/StandardTab.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/ButtonControl/CheckboxTextbuttonView/CheckboxTextbuttonView.swift
Accessability Button SwiftUI
Accessability Button SwiftUI
> [613] - Accessability Button SwiftUI

- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Calendar/Horizontal/HorizontalViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Calendar/Vertical/VerticalCalendarViewController.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/CalendarView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/Common/Cells/CalendarViewCell.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/Common/Views/CalendarHorizontalHeaderView/CalendarHorizontalHeaderView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/HorizontalCalendar/CalendarHorizontalView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/HorizontalCalendar/Cell/CalendarHorizontalViewCell.swift
- Source/AdmiralUIKit/Classes/Components/Views/Calendar/VerticalCalendar/CalendarVerticalView.swift
Добавить AccessibilityIds для календаря
> [612] - Added AccessibilityIds for calendar

- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Cells/ActionBar/ActionBarViewModel.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Cells/BaseCell/LeadingComponentsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Cells/BaseCell/TralingComponentsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Cells/ImageBaseCell/ImageBaseCellLeadingViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Cells/ImageBaseCell/ImageBaseCellTralingViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Cells/TitleBaseCell/PrimaryTitleCellViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Cells/TitleBaseCell/SecondaryTitleCelViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Currency/DefaultCurrency/DefaultCurrencyViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Currency/FlagsCurrency/FlagsCurrencyViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Currency/IconsCurrency/IconsCurrencyViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Currency/IconsFlagsCurrency/IconsFlagsCurrencyViewController.swift
- Source/AdmiralUIKit/Classes/Components/Controls/CheckControl/CheckTextControl/CheckTextControl.swift
- Source/AdmiralUIKit/Classes/Components/Views/Cell/ActionBarCell/ActionBarIItemButton/ActionBarItemDefault/ActionIBarDefaultItemControl/ActionItemBarDefaultControl.swift
- Source/AdmiralUIKit/Classes/Components/Views/Cell/ActionBarCell/ActionBarIItemButton/ActionBarItemDefault/ActionItemBarDefaultView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Cell/ActionBarCell/ActionBarIItemButton/ActionBarItemSecondary/ActionItemBarViewSecondary.swift
- Source/AdmiralUIKit/Classes/Components/Views/Cell/ActionBarCell/ActionBarItem/ActionItemBarAction.swift
- Source/AdmiralUIKit/Classes/Components/Views/Cell/View/Center/TitleSubtitleButtonListView/TitleSubtitleButtonListView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Cell/View/Traling/ButtonListView/ButtonListView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Cell/View/Traling/ButtonWithArrowListView/ButtonWithArrowListView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Cell/View/Traling/CheckBoxListView/CheckBoxListView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Cell/View/Traling/RadioButtonListView/RadioButtonListView.swift
- Source/AdmiralUIKit/Classes/Components/Views/Cell/View/Traling/SwitchListView/SwitchListView.swift
> [612] - Added Accessibility for cells 

- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/IconTabs/IconTabsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/InformerTabs/InformerTabViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/LogoTabs/LogoTabsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/OutlineSliderTabs/OutlineSliderTabsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/StandardTabs/StandardTabsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/UnderlineTabs/UnderlineCenterTabs/UnderlineCenterTabs.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/UnderlineTabs/UnderlineSliderTabs/UnderlineSliderTabs.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Tab/IconTab/IconTabsSegmentControl.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Tab/InformerTab/InformerSegmentedControl/InformerTabSegmentedControl.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Tab/SlideTab/OutlineSliderTab/OutlineSliderSegmentedControl/OutlineSliderCollectionViewCell.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Tab/SlideTab/OutlineSliderTab/OutlineSliderSegmentedControl/OutlineSliderSegmentedControl.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Tab/SlideTab/UnderlineSliderTab/UnderlineSegmentedControl/UnderlineSliderViewCell.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Tab/SlideTab/UnderlineSliderTab/UnderlineSegmentedControl/UnderlineTabsSegmentedControl.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Tab/StandardTab/LogoSegmentedControl/LogoSegmentedControl.swift
- Source/AdmiralUIKit/Classes/Components/Controls/Tab/StandardTab/StandardSegmentedControl/StandardSegmentedControl.swift
> [612] - Tabs Accessibility UIKit

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/CustomSwiftUIViewModel.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/MainViewController.swift
https://github.com/admiral-team/admiralui-ios/issues/482
> [482] - Fix finding main page

- version.json
> [BUMP] - 11.1.1

- ExampleiOS/Source/Classes/UserStrories/Common/View/ThemeSwitchView/ThemeSwitchViewCoordinator.swift
https://github.com/admiral-team/admiralui-ios/issues/656
> [656] - Add accessibilityIdentifier to theme buttons

- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/MainViewController.swift
https://github.com/admiral-team/admiralui-ios/issues/560
> [560] - Fix finding checkbox

- ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextFields/TextField/Number/Default/InputNumberDefaultSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextFields/TextField/Number/Secondary/InputNumberSecondarySwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/BottomSheet/BottomSheetBottomView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/BottomSheet/BottomSheetExampleViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/BottomSheet/BottomSheetTableViewCell.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/BottomSheet/BottomSheetViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/UnderlineTabs/UnderlineCenterTabs/UnderlineCenterTabs.swift
https://github.com/admiral-team/admiralui-ios/issues/664
> [664] - Add accessibility to bottom sheet

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Checkbox/CheckboxViewController.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUICheckboxTest.swift
> [559] - Add UI test for Checkbox

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/TagsChips/TagsChipsViewController.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUITagsandChipsTest.swift
> [555] - Add UI test for Tags & Chips with accessibility

- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/TextBlocks/DropDown/DropDownViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/TextBlocks/Links/LinksHeaderViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/TextBlocks/Paragraph/ParagraphViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/TextBlocks/Separator/SeparatorViewController.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUITextBlocksTest.swift
Заменил в готовом тесте accessibility
> [338] - Changed UI test with accessibility for Text blocks

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
- ExampleiOS/Source/Classes/UserStrories/Info/FAQViewController/FAQViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Buttons/GhostButtons/GhostButtonViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Buttons/OtherButtons/OtherButtonsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Buttons/PrimaryButton/PrimaryButtonsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Buttons/Rules/RulesViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Buttons/SecondaryButton/SecondaryButtonsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Icons/IconsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/PageControls/CircularPageControl/CircularPageControlViewController.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AddUIKitSpinnerTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIIconsTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitButtonsTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitFAQTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitInfoTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIPageControlsCircleTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIThemesTest.swift
1)https://github.com/admiral-team/admiralui-ios/issues/584
2)https://github.com/admiral-team/admiralui-ios/issues/563
3)https://github.com/admiral-team/admiralui-ios/issues/670
4)https://github.com/admiral-team/admiralui-ios/issues/588
5)https://github.com/admiral-team/admiralui-ios/pull/658
Написаны UI тесты для экранов - Themes, Icons, Buttons, Info, FAQ, Spinner, Page Controls Circle
> [Feature] - 584 563 670 588 331 tests

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
- ExampleiOS/Source/Classes/UserStrories/Info/FAQViewController/FAQViewController.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitFAQTest.swift
> [588] - Add UI test for FAQ

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/PageControls/CircularPageControl/CircularPageControlViewController.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIPageControlsCircleTest.swift
Add UI test for Page Controls Circle
> [670] - Add UI test for Page Controls Circle

- ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Buttons/GhostButtons/GhostButtonViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Buttons/OtherButtons/OtherButtonsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Buttons/PrimaryButton/PrimaryButtonsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Buttons/Rules/RulesViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Buttons/SecondaryButton/SecondaryButtonsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Icons/IconsViewController.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIIconsTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitButtonsTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIThemesTest.swift
> [331] - Changed UI test with accessibility (Themes - Icons - Buttons)

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Links/LinksViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/PageControls/LinerPageControl/LinerPageControl.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/RadioButton/RadioButtonViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Switcher/SwitcherViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/IconTabs/IconTabsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/InformerTabs/InformerTabViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/LogoTabs/LogoTabsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/OutlineSliderTabs/OutlineSliderTabsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/StandardTabs/StandardTabsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/UnderlineTabs/UnderlineCenterTabs/UnderlineCenterTabs.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Tabs/UnderlineTabs/UnderlineSliderTabs/UnderlineSliderTabs.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AddUIKitLinkTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AddUIKitPageControlsTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitTabsTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitZeroscreenTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIRadiobuttonTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUISwitcherTest.swift
https://github.com/admiral-team/admiralui-ios/pull/601
https://github.com/admiral-team/admiralui-ios/pull/564
https://github.com/admiral-team/admiralui-ios/pull/650
https://github.com/admiral-team/admiralui-ios/pull/648
https://github.com/admiral-team/admiralui-ios/pull/568#pullrequestreview-1219427406
https://github.com/admiral-team/admiralui-ios/pull/552
> [660 564 557 646 567 550] - tests

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitZeroscreenTest.swift
Добавлен UI тест для Zeroscreen
> [600] - Add UI test for Zeroscreen

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIIconsTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitContactsTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIKitCurrencyTest.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIOnboardingTest.swift
> [582, 598, 602, 586] - tests

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Cells/ActionBar/ActionBarViewModel.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Cells/ActionBar/ActionBarsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Cells/BaseCell/CenterElements/CenterElementsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Cells/BaseCell/LeadingElements/LeadingElementsViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Cells/BaseCell/TralingElements/TralingElementsViewController.swift
- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUICellsTest.swift
> [683] - Add Ui test for Cells

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/Representable/ThemeSwitchView/ThemeSwitchSwiftUIView.swift
> [685] - Add ellipse identifier

- ExampleiOS/Source/Classes/UserStrories/Common/Base/BaseTabBarController.swift
- ExampleiOS/Source/Classes/UserStrories/Settings/Cells/SwitcherListTableViewCell.swift
- ExampleiOS/Source/Classes/UserStrories/Settings/SettingsViewController.swift
https://github.com/admiral-team/admiralui-ios/issues/694
> [694] - Add accessibility for TabBars items and in switchers in Seating screen

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/ActionBar/ActionBarSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/BaseCell/LeadingComponents/LeadingComponentsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/BaseCell/TralingComponents/TralingComponentsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/ImageBaseCell/LableComponents/ImageLableComponentsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/DropDown/DropDownSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/Headers/HeadersSwiftUIView.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/CheckControl/CheckBox.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/CheckControl/RadioControl.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Cell/ActionBarCell/ActionBarItem/ActionItemBarAction.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Cell/ActionBarCell/ActionBarView/ActionBarView.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Cell/Trailing/ButtonListView/ButtonListView.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Cell/Trailing/ButtonWithArrowListView/ButtonWithArrowListView.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Cell/Trailing/CheckBoxListView/CheckBoxListView.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Cell/Trailing/RadioButtonListView/RadioButtonListView.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/TextBlock/DropDown/ButtonDropDown.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/TextBlock/DropDown/TitleButtonDropDown.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/TextBlock/Headers/ArrowWithButton/TitleArrowWithButtonHeader.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/TextBlock/Link/LinkView.swift
https://github.com/admiral-team/admiralui-ios/issues/687
> [687] - Add accesibilityId to Cells & TextBlocks

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/GhostButton/GhostButtonSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/Otherbuttons/OtherButtonsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/PrimaryButtons/PrimaryButtonsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/Rules/RulesSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/SecondaryButtons/SecondaryButtonsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/BaseCell/LeadingComponents/LeadingComponentsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/BaseCell/TralingComponents/TralingComponentsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/ImageBaseCell/LableComponents/ImageLableComponentsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/Representable/ThemeSwitchView/ThemeSwitchSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/IconTabs/IconTabs.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/InformerTabs/InformerTabSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/Logo/LogoTabSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/OutlineSliderTab/OutlineSliderTabSwiftUITab.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/Standard/StandardTabSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/UnderlineSliderTab/UnderlineCenterTabsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/UnderlineSliderTab/UnderlineSliderTabSwiftUIView.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUITestsLaunchTests.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/IconTab/IconTab.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/InformerTab/InformerTab.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/LogoTab/LogoTab.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/OutlineSliderTab/OutlineSliderTab.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/OutlineSliderTab/OutlineSliderTabItem.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/StandardTab/StandardTab.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/UnderlineSliderTab/UnderlineTab.swift
- Source/AdmiralSwiftUI/Classes/Components/Controls/SegmentControl/UnderlineSliderTab/UnderlineTabItem.swift
https://github.com/admiral-team/admiralui-ios/issues/699
> [699] - Fix segment controll theme switcher identifier

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/GhostButton/GhostButtonSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/Otherbuttons/OtherButtonsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/PrimaryButtons/PrimaryButtonsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/Rules/RulesSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/SecondaryButtons/SecondaryButtonsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/InformerTabs/InformerTabSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/Logo/LogoTabSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/Standard/StandardTabSwiftUIView.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUIButtonsTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUITabsTest.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/ButtonControl/CheckboxTextbuttonView/CheckboxTextbuttonView.swift
> [692] - Add UI test for SwiftUI Buttons, Tabs

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Alert&Onboarding/AlertOnboardingSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Buttons/ButtonsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Calendar/CalendarsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/CellsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Informers/InformersSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/InformersAndToastsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Notifications /NotificationsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/SwiftUIController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/PageControls/PageControlsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Tabs/TabsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/TextBlocksSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextFields/TextFieldsSwiftUIView.swift
https://github.com/admiral-team/admiralui-ios/issues/711
> [711] - Accessibility and fix tests for navigation cells

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/ActionBar/ActionBarSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/BaseCell/LeadingComponents/LeadingComponentsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/BaseCell/TralingComponents/TralingComponentsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/ImageBaseCell/LableComponents/ImageLableComponentsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/TextBaseCell/TextBaseCellSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/TitleBaseCell/Primary/PrimaryTitleBaseCellSwiftUI.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/TitleBaseCell/Secondary/SecondaryTitleBaseCellSwiftUI.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/DropDown/DropDownSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/Link/LinkSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/Paragraph/ParagraphSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TextBlocks/Separator/SeparatorSwiftUIView.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUICellsTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUICellsTextBlockTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUITextBlocksTest.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Cell/ActionBarCell/ActionBarView/ActionBarView.swift
> [704] - Add UI test for SwiftUI Cells and Text Block

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Informers/BigInformers/BigInformersSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Informers/SmallInformers/SmallInformersSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Notifications /ActionNotification/ActionNotificationSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Notifications /StaticNotifications/StaticNotificationsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Notifications /ToastNotifications/ToastNotificationsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/InformersAndToasts/Notifications /ToastNotifications/ToastNotificationsViewModel.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Main/SwiftUIController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/PageControls/CircularPageControl/CircularPageControlSwiftUI.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/PageControls/LinerPageControl/LinerSwiftUIView.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUICircularPageControlTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUIInformersAndNotificationsTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUILinerPageControl.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Informers/BigInfomer/BigInformer.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Toast/ToastPresenter.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Toast/ToastView.swift
https://github.com/admiral-team/admiralui-ios/issues/709
> [709] - Add UI  tests for SwiftUI ( informers&notifications, page controls)

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/CheckBox/CheckBoxSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Links/LinksSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/RadioButtons/RadioButtonSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Spinner/SpinnerSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Switcher/SwitcherSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/TagsChips/TagsChipsSwiftUIView.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUICheckboxTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUILinksTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUIRadiobuttonTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUISpinnerTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUISwitcherTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUITagsAndChipsTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUITestsLaunchTests.swift
> [707] - Add UI tests for SwiftUI (Radiobutton, Tags&Chips, Checkbox, Switcher, Links, Spinner)

- AdmiralUI.xcodeproj/project.pbxproj
- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
- ExampleiOS/Source/Classes/UserStrories/Info/Cells/InfoMainCell.swift
- ExampleiOS/Source/Classes/UserStrories/Info/Cells/MenuInfoCell.swift
- ExampleiOS/Source/Classes/UserStrories/Info/InfoViewController.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Alert&Onboarding/Alert/AlertSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Alert&Onboarding/Error/ErrorSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Alert&Onboarding/OnBoarding/OnBoardingSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Alert&Onboarding/ZeroScreen/ZeroScreenSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Currency/DefaultCurrency/DefaultCurrencySwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Currency/FlagsCurrency/FlagsCurrencySwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Currency/IconsCurrency/IconsCurrencySwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Currency/IconsFlagsCurrency/IconsFlagsCurrencySwiftUIView.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUIAlertTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUIContactsTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUICurrencyTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUIFAQTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUIInfoTest.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Alert/AlertView.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Alert/AlertViewAccessibilityIdentifiers.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/ErrorView/ErrorView.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/ZeroScreen/ZeroScreenView.swift
> [714] - Add UI test for SwiftUI for (Alert, Contacts, FAQ, Currency, Info)

- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Classes/CoreFoundation/Assets/Assets.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/BaseCell/BaseCellSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/BaseCell/CenterElements/CenterElementsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/BaseCell/LeadingElements/LeadingElementsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/BaseCell/TralingElements/TralingElementsSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Cells/ImageBaseCell/ImageBaseCellSwiftUIView.swift
https://github.com/admiral-team/admiralui-ios/issues/693
> [693] - Fix Cells flow

- Scripts/upload_nexus_lib.command
- Scripts/upload_nexus_lib_current_branch.command
- fastlane/Fastfile
- fastlane/Pluginfile
- fastlane/go_scripts/go.sum
- fastlane/go_scripts/main.go
- fastlane/go_scripts/nexus/createBodyRequest.go
- fastlane/go_scripts/nexus/nexusParameter.go
- fastlane/go_scripts/nexus/upload.go
- fastlane/nexus_info.rb
> [581] - added nexus upload scripts with golang

- AdmiralSwiftUI.podspec
- AdmiralTheme.podspec
- AdmiralUIKit.podspec
- AdmiralUIResources.podspec
- ExampleiOS/Source/Supporting Files/Info.plist
- Source/AdmiralCore/Supporting Files/Info.plist
- Source/AdmiralSwiftUI/Supporting Files/Info.plist
- Source/AdmiralTheme/Supporting Files/Info.plist
- Source/AdmiralUIKit/Supporting Files/Info.plist
- Source/AdmiralUIResources/Supporting Files/Info.plist
- Tests/AdmiralSwiftUITests/Supporting Files/Info.plist
- Tests/AdmiralUIKitTests/Supporting Files/Info.plist
- version.json
> [BUMP] - 11.2.0

- .github/workflows/ios.yml
- AdmiralSwiftUI.podspec
- AdmiralTheme.podspec
- AdmiralUIKit.podspec
- AdmiralUIResources.podspec
- ExampleiOS/ExampleiOS.xcodeproj/project.pbxproj
- ExampleiOS/Source/Supporting Files/Info.plist
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUIButtonsTest.swift
- ExampleiOS/Tests/AdmiralSwiftUITests/AdmiralSwiftUICircularPageControlTest.swift
- ExampleiOS/Tests/ForceTapElement.swift
- Source/AdmiralCore/Supporting Files/Info.plist
- Source/AdmiralSwiftUI/Supporting Files/Info.plist
- Source/AdmiralTheme/Supporting Files/Info.plist
- Source/AdmiralUIKit/Supporting Files/Info.plist
- Source/AdmiralUIResources/Supporting Files/Info.plist
- Tests/AdmiralSwiftUITests/Supporting Files/Info.plist
- Tests/AdmiralUIKitTests/Supporting Files/Info.plist
- version.json
> [HOTFIX] - 11.2.1

- .github/workflows/ios.yml
- AdmiralCore.podspec
- AdmiralSwiftUI.podspec
- AdmiralTheme.podspec
- AdmiralUIKit.podspec
- AdmiralUIResources.podspec
- ExampleiOS/Source/Supporting Files/Info.plist
- Source/AdmiralCore/Supporting Files/Info.plist
- Source/AdmiralSwiftUI/Supporting Files/Info.plist
- Source/AdmiralTheme/Supporting Files/Info.plist
- Source/AdmiralUIKit/Classes/Components/Views/Cell/ActionBarCell/ActionBarView/ActionBarView.swift
- Source/AdmiralUIKit/Supporting Files/Info.plist
- Source/AdmiralUIResources/Supporting Files/Info.plist
- Tests/AdmiralSwiftUITests/Supporting Files/Info.plist
- Tests/AdmiralUIKitTests/Supporting Files/Info.plist
- version.json
> [HOTFIX] - 11.2.2

- fastlane/Fastfile
- fastlane/go_scripts/go.mod
- fastlane/go_scripts/go.sum
- fastlane/go_scripts/main.go
> [767] - Go release

- checksum.json
- fastlane/.env
- fastlane/Fastfile
- fastlane/checksum.rb
> [767] - Checksums

- Source/AdmiralSwiftUI/Classes/Components/Views/TextFields/Sliders/InputRangeTextField/InputRangeTextField.swift
https://github.com/admiral-team/admiralui-ios/issues/783
> [783] - Fix slider flexibility

- Source/AdmiralUIKit/Classes/Components/Views/TextFields/Common/TextInputDecorationView.swift
- Source/AdmiralUIKit/Classes/Components/Views/TextFields/DoubleInputRangeTextField/DoubleInputRangeTextField.swift
https://github.com/admiral-team/admiralui-ios/issues/753
> [753] - Double text UIKit

- Source/AdmiralUIKit/Classes/Components/Views/Cell/ListCellView/ListCell.swift
https://github.com/admiral-team/admiralui-ios/issues/799
> [799] - Add offsets for list cell

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Calendar/CalendarSwiftUIView.swift
- Source/AdmiralSwiftUI/Classes/Components/Views/Calendar/CalendarVerticalView/CalendarVerticalView.swift
https://github.com/admiral-team/admiralui-ios/issues/798
> [798] - Fix vertical calendar SwiftUI

- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Alert&Onboarding/Alert/AlertSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Alert&Onboarding/Error/ErrorSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Alert&Onboarding/OnBoarding/OnBoardingSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Alert&Onboarding/ZeroScreen/ZeroScreenSwiftUIView.swift
- ExampleiOS/Source/Classes/UserStrories/Main/UIKit/Alert&Onboarding/AlertOnboardingViewController.swift
https://github.com/admiral-team/admiralui-ios/issues/745
> [745] - Alerts(Zeroscreen, Onboarding, Error View)

- version.json
> [BUMP] - 24

- ExampleiOS/Tests/AdmiralUIKitTests/AdmiralUIOnboardingTest.swift
> [HOTFIX] - 12.0.0 rc hotfix tests

- .github/workflows/ios.yml
- fastlane/Fastfile
Fix lane validate_depenecy_managers
Remove bundle update fastlane
> [HOTFIX] - Fix validate depenecy 

- AdmiralUI.xcodeproj/project.pbxproj
- Source/AdmiralCalendarSwiftUI/Classes/Calendar/CalendarDaysView/CalendarDaysView.swift
- Source/AdmiralCalendarSwiftUI/Classes/Calendar/CalendarGenerator.swift
- Source/AdmiralCalendarSwiftUI/Classes/Calendar/CalendarHorizontalView/CalendarHorizontalView.swift
- Source/AdmiralCalendarSwiftUI/Classes/Calendar/CalendarVerticalView/CalendarVerticalView.swift
- Source/AdmiralCalendarSwiftUI/Classes/Calendar/CalendarView/CalendarView.swift
- Source/AdmiralCalendarSwiftUI/Classes/Extensions/Foundation/DateFormatter/Date+isBetween.swift
- Ручка с отступом между датами
- Ручка с массивом выбранных дат
> [869] - Визуальные доработки по календарю

- version.json
> [BUMP] - 13.0.0

- AdmiralCalendarSwiftUI.podspec
- AdmiralCore.podspec
- AdmiralImages.podspec
- AdmiralSwiftUI.podspec
- AdmiralSymbols.podspec
- AdmiralTheme.podspec
- AdmiralUI.xcodeproj/project.pbxproj
- AdmiralUIKit.podspec
- ExampleiOS/Source/Classes/UserStrories/Main/SwiftUI/Calendar/CalendarSwiftUIView.swift
- ExampleiOS/Source/Supporting Files/Info.plist
- Source/AdmiralCalendarSwiftUI/Classes/Calendar/CalendarDaysView/CalendarDaysView.swift
- Source/AdmiralCalendarSwiftUI/Classes/Calendar/CalendarVerticalView/CalendarPaginator.swift
- Source/AdmiralCalendarSwiftUI/Classes/Calendar/CalendarVerticalView/CalendarVerticalPaginator.swift
- Source/AdmiralCalendarSwiftUI/Classes/Calendar/CalendarVerticalView/CalendarVerticalView.swift
- Source/AdmiralCalendarSwiftUI/Classes/Calendar/CalendarVerticalView/InversedScrollView.swift
- Source/AdmiralCalendarSwiftUI/Classes/Calendar/CalendarView/CalendarView.swift
- Source/AdmiralCalendarSwiftUI/Classes/Calendar/CalendarWeekView/CalendarWeekView.swift
- Source/AdmiralCalendarSwiftUI/Supporting Files/Info.plist
- Source/AdmiralCore/Supporting Files/Info.plist
- Source/AdmiralImages/Supporting Files/Info.plist
- Source/AdmiralSwiftUI/Supporting Files/Info.plist
- Source/AdmiralSymbols/Supporting Files/Info.plist
- Source/AdmiralTheme/Supporting Files/Info.plist
- Source/AdmiralUIKit/Supporting Files/Info.plist
- Tests/AdmiralSwiftUITests/Supporting Files/Info.plist
- Tests/AdmiralUIKitTests/Supporting Files/Info.plist
- version.json
> [HOTFIX] - 13.0.2

- version.json
> [BUMP] - 13.0.3
